create DATABASE DB_carros
GO

use DB_carros
GO

create table Carros(
        carro VARCHAR(20),
        fabricante VARCHAR(30)
);
GO

INSERT INTO CARROS VALUES('KA','FORD')
INSERT INTO CARROS VALUES('FIESTA','FORD')
INSERT INTO CARROS VALUES('PRISMA','FORD')
INSERT INTO CARROS VALUES('CLIO','RENAULT')
INSERT INTO CARROS VALUES('SANDERO','RENAULT')
INSERT INTO CARROS VALUES('CHEVETE','CHEVROLET')
INSERT INTO CARROS VALUES('OMEGA','CHEVROLET')
INSERT INTO CARROS VALUES('PALIO','FIAT')
INSERT INTO CARROS VALUES('DOBLO','FIAT')
INSERT INTO CARROS VALUES('UNO','FIAT')
INSERT INTO CARROS VALUES('GOL','VOLKSWAGEN')
GO

DECLARE
    @Quant_fiat int;
BEGIN
    set @Quant_fiat = (select count(*) from Carros where fabricante = 'FIAT');
    PRINT 'Quantidade de carros da FIAT: ' + cast(@Quant_fiat as varchar);
END
GO